{{- if .Values.acme.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "issuer.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.global.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- range $key, $value := .Values.global.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  acme:
    email: {{ .Values.acme.email | quote }}
    server: {{ .Values.acme.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.acme.privateKeySecretRef | quote }}
    solvers:
    {{- if .Values.acme.solvers }}
    {{- range .Values.acme.solvers }}
    - selector:
        {{- if .selector.dnsZones }}
        dnsZones:
          {{- toYaml .selector.dnsZones | nindent 10 }}
        {{- else }}
        {}
        {{- end }}
      {{- if .dns01 }}
      dns01:
        {{- range $dnsSolver := .dns01 }}
        {{- toYaml $dnsSolver | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .http01 }}
      http01:
        {{- range $httpSolver := .http01 }}
        {{- toYaml $httpSolver | nindent 8 }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- else }}
    []
    {{- end }}
{{- end }}

{{- if .Values.selfSigned.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "issuer.fullname" . }}-self-signed
spec:
  selfSigned: {}
{{- end }}

{{- if .Values.vault.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "issuer.fullname" . }}-vault
  annotations:
    {{- range $key, $value := .Values.global.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- range $key, $value := .Values.global.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  vault:
    server: {{ .Values.vault.server | quote }}
    path: {{ .Values.vault.path | quote }}
    auth:
      tokenSecretRef:
        name: {{ .Values.vault.auth.tokenSecretRef.name | quote }}
        key: {{ .Values.vault.auth.tokenSecretRef.key | quote }}
{{- end }}
