{{- if .Values.acme.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "issuer.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.global.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- range $key, $value := .Values.global.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  acme:
    email: {{ .Values.acme.email | quote }}
    server: {{ .Values.acme.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.acme.privateKeySecretRef | quote }}
    solvers:
    {{- range .Values.acme.solvers }}
    - selector:
        {{- if .selector.dnsZones }}
        dnsZones:
          {{- toYaml .selector.dnsZones | nindent 10 }}
        {{- end }}
      {{- if .dns }}
      dns:
        {{- range $solverType, $solverConfig := .dns }}
        {{ $solverType }}:
          {{- toYaml $solverConfig | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .http01 }}
      http01:
        {{- toYaml .http01 | nindent 8 }}
      {{- end }}
      {{- if .ca }}
      ca:
        {{- toYaml .ca | nindent 8 }}
      {{- end }}
      {{- if .vault }}
      vault:
        {{- toYaml .vault | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}

{{- if .Values.selfSigned.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "issuer.fullname" . }}-self-signed
spec:
  selfSigned: {}
{{- end }}
