{{- if .Values.acme.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "issuer.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.global.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- range $key, $value := .Values.global.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  acme:
    email: {{ .Values.acme.email | quote }}
    server: {{ .Values.acme.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.acme.privateKeySecretRef | quote }}
    solvers:
    {{- if .Values.acme.solvers }}
    {{- range .Values.acme.solvers }}
    - selector:
        {{- if .dnsZones }}
        dnsZones:
        {{ toYaml .dnsZones | nindent 8 }}
        {{- end }}
      dns01:
        {{- with .route53 }}
        route53:
          region: {{ .region | quote }}
          hostedZoneID: {{ .hostedZoneID | quote }}
        {{- end }}
        {{- with .cloudflare }}
        cloudflare:
          apiTokenSecretRef:
            name: {{ .apiTokenSecretRef.name | quote }}
            key: {{ .apiTokenSecretRef.key | quote }}
        {{- end }}
        {{- with .azure }}
        azureDNS:
          clientID: {{ .clientID | quote }}
          clientSecretSecretRef:
            name: {{ .clientSecretSecretRef.name | quote }}
            key: {{ .clientSecretSecretRef.key | quote }}
          tenantID: {{ .tenantID | quote }}
          subscriptionID: {{ .subscriptionID | quote }}
          hostedZoneName: {{ .hostedZoneName | quote }}
        {{- end }}
        {{- with .gcp }}
        googleDNS:
          project: {{ .project | quote }}
          serviceAccountSecretRef:
            name: {{ .serviceAccountSecretRef.name | quote }}
            key: {{ .serviceAccountSecretRef.key | quote }}
        {{- end }}
    {{- end }}
    {{- else }}
    - selector: {}
      dns01: {}
    {{- end }}
{{- end }}

{{- if .Values.selfSigned.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "issuer.fullname" . }}-self-signed
spec:
  selfSigned: {}
{{- end }}
