{{- /*
Copyright Six After, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.acme.privateKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.acme.privateKeySecretRef }}
  namespace: {{ .Values.certManagerNamespace | default "cert-manager" }}
  annotations:
    {{- range $key, $value := .Values.global.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- range $key, $value := .Values.global.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
type: Opaque
data:
  tls.key: {{ .Values.acme.privateKey.data | default "" }}
{{- end }}
