# Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: ci

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - 'main'

    paths:
      - charts/** 
      - .github/workflows/publish.yaml

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Required to read repo contents
      packages: write # Required to push to GHCR

    steps:
      - name: Display GitHub Context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Display Job Context
        run: echo '${{ toJSON(job) }}'
      - name: Display Steps Context
        run: echo '${{ toJSON(steps) }}'
      - name: Display Runner Context
        run: echo '${{ toJSON(runner) }}'
      - name: Display Strategy Context
        run: echo '${{ toJSON(strategy) }}'
      - name: Display Matrix Context
        run: echo '${{ toJSON(matrix) }}'

      - name: Preamble
        run: |
          whoami
          echo github ref $GITHUB_REF
          echo workflow $GITHUB_WORKFLOW
          echo home $HOME
          echo event name $GITHUB_EVENT_NAME
          echo workspace $GITHUB_WORKSPACE

          df -h

      # Ref: https://github.com/actions/checkout
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Ref: https://github.com/helm/chart-testing-action
      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml
