# Copyright (c) 2024 Six After, Inc.
#
# This source code is licensed under the Apache 2.0 License found in the
# LICENSE file in the root directory of this source tree.

# Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: publish

on:
  workflow_dispatch:
    
  push:
    branches:
      - 'main'
  
    paths:
      - charts/** 
      - .github/workflows/publish.yaml

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Required to read repo contents
      packages: write # Required to push to GHCR

    steps:
      - name: Preamble
        run: |
          whoami
          echo github ref $GITHUB_REF
          echo workflow $GITHUB_WORKFLOW
          echo home $HOME
          echo event name $GITHUB_EVENT_NAME
          echo workspace $GITHUB_WORKSPACE
          
          df -h

      - name: Install yq (mikefarah version)
        run: |
          sudo apt remove -y yq || true
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          yq --version  # Verify installation

      # Ref: https://github.com/actions/checkout
      - name: Checkout Source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"          

      # Ref: https://github.com/Azure/setup-helm
      # https://helm.sh/docs/intro/install#from-apt-debianubuntu
      # - name: Install Helm
      #   uses: azure/setup-helm@v4
      #   with:
      #       version: 'v3.19.0'
        # run: | 
        #   sudo apt-get install curl gpg apt-transport-https --yes
        #   curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        #   echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        #   sudo apt-get update
        #   sudo apt-get install helm

      # Ref: https://github.com/Azure/setup-helm
      - name: Setup Helm
        id: setup-helm
        continue-on-error: true
        uses: azure/setup-helm@v4
        with:
            version: 'v3.19.0'

      - name: Set up Homebrew
        id: setup-homebrew
        if: ${{ steps.setup-helm.outcome == 'failure' }}
        uses: Homebrew/actions/setup-homebrew@main

      - name: Install Helm
        id: install-helm
        if: ${{ steps.setup-helm.outcome == 'failure' }}
        shell: bash
        run: |
          brew install helm

      # Authenticate to GHCR
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      # Ref: https://github.com/helm/chart-testing-action
      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Last Commit Before Merge
        id: last-commit
        run: |
          LAST_COMMIT=$(git rev-parse HEAD^)
          echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_ENV

      # Detect changed charts.
      # Ref: https://github.com/helm/chart-testing-action
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml --since "$LAST_COMMIT" | sed 's|charts/||g')
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            {
              echo 'charts<<EOF'
              echo "$changed"
              echo 'EOF'
            } >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Debug changed charts
        run: |
          echo "Changed charts:"
          echo "${{ steps.list-changed.outputs.charts }}"

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config ct.yaml

      # Publish Changed Charts.
      - name: Publish Charts
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          while IFS= read -r chart; do
            echo "Processing chart: $chart"

            # Extract chart version from Chart.yaml
            VERSION=$(yq eval '.version' charts/$chart/Chart.yaml)

            # Package the chart
            helm package charts/$chart --destination ./charts-packaged

            # Push the chart
            helm push ./charts-packaged/$chart-$VERSION.tgz oci://ghcr.io/${{ github.repository_owner }}/charts/
          done <<< "${{ steps.list-changed.outputs.charts }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GITHUB_USER: ${{ secrets.GHCR_USER }}
